name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true --self-contained false
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DevOpsScraper
        path: /home/runner/work/WebScraping/WebScraping/bin/Release/net6.0/win-x64/publish/
